version: 2.1
orbs:
  ruby: circleci/ruby@1.5.0
  codecov: codecov/codecov@3.2.2
  browser-tools: circleci/browser-tools@1.1

jobs:
  test:
    parallelism: 1
    parameters:
      ruby-version:
        type: string
    working_directory: ~/project
    resource_class: small
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    environment:
      RAILS_ENV: test
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
    steps:
      - add_ssh_keys:
          fingerprints:
            - '91:82:dc:42:95:4f:4a:3b:db:32:5c:bc:c7:08:c8:6e'
      - checkout
      - run: ruby --version
      - ruby/install-deps:
          with-cache: false
      - ruby/rspec-test
      - store_test_results:
          path: /tmp/test-results/rspec/results.xml
      - codecov/upload:
          file: /tmp/test-results/rspec/results.xml
workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              # https://github.com/CircleCI-Public/cimg-ruby
              # only supports the last three ruby versions
              ruby-version: ["3.3", "3.2", "3.1"]
